# tr <- read.enewick2("../beast_arg.newick")
# ftr <- fortify.evonet(phylo)
# #p <- ggplot(ftr) + geom_arg(retcol = "black", arrow = F) + geom_nodelab(size=2) + geom_tiplab(size=2) + geom_retlab() + theme_tree()
# p <- ggplot(ftr) + geom_arg(retcol = "black", arrow = F) + geom_nodelab() + geom_tiplab() + geom_retlab() + theme_tree()
# # # pdf("treeplot.pdf", paper = "a4r")
# plot(p)
# # # dev.off()
